from django.db import models

# Create your models here.
class Storm_App(models.Model):
	projname = models.CharField(max_length=32)
	app_date = models.DateTimeField(auto_now_add=True)
	projectlocation = models.CharField(max_length=32)
	owner_fnam = models.CharField(max_length=32)
	owner_lname = models.CharField(max_length=32)
	owner_address = models.CharField(max_length=32)
	phonenumber = models.CharField(max_length=16)
	tceq_noi = models.CharField(max_length=16)
	site_contact_fname = models.CharField(max_length=32)
	site_contact_lname = models.CharField(max_length=32)
	site_contactphone = models.IntegerField()
	site_contactemail = models.EmailField()
	inspect_fname = models.CharField(max_length=32)
	inspect_lname = models.CharField(max_length=32)
	inspect_phone = models.IntegerField()
	inspect_email = models.EmailField()
	startdate = models.DateField()
	plat_id = models.CharField(max_length=16)
	lot_id = models.CharField(max_length=16)
	block_id = models.CharField(max_length=16)
	#file upload?

	def __str__(self):
		return (self.projname)


class Ossf(models.Model):
	app_date = models.DateTimeField(auto_now_add=True)
	owner_fname = models.CharField(max_length=32)
	owner_lname = models.CharField(max_length=32)
	owner_addr = models.CharField(max_length=32)
	owner_city = models.CharField(max_length=32)
	owner_state = models.CharField(max_length=2)
	owner_zipcode = models.CharField(max_length=5)
	owner_phone = models.IntegerField()
	owner_email = models.EmailField()
	agent_fname = models.CharField(max_length=32)
	agent_lname = models.CharField(max_length=32)
	agent_addr = models.CharField(max_length=32)
	agent_city = models.CharField(max_length=32)
	agent_state = models.CharField(max_length=2)
	agent_zipcode = models.CharField(max_length=5)
	agent_phone = models.IntegerField()
	agent_email = models.EmailField()
	subdivision_name = models.CharField(max_length=16)
	plat_id = models.CharField(max_length=16)
	lot_id = models.CharField(max_length=16)
	block_id = models.CharField(max_length=16)
	acre = models.IntegerField()
	legal_desc = models.CharField(max_length=16)
	prop_addr = models.CharField(max_length=32)
	prop_city = models.CharField(max_length=32)
	prop_zip = models.CharField(max_length=5)
	startdate = models.DateField()
	single_type = models.BooleanField()
	single_facility = models.CharField(max_length=16)
	bedrooms = models.IntegerField()
	sq_ft = models.IntegerField()
	commercial = models.BooleanField()
	comm_facility = models.CharField(max_length=16)
	facility_occp = models.IntegerField()
	facility_seats = models.IntegerField()
	facility_beds = models.IntegerField()
	bldg_costs = models.IntegerField()
	FEMA_yes = models.BooleanField()
	FEMA_no = models.BooleanField()
	SE_yes = models.BooleanField()
	SE_no = models.BooleanField()
	site_eval_name = models.CharField(max_length=32)
	sys_descrip = models.TextField()
	tanksize = models.IntegerField()
	app_area_size = models.IntegerField()
	gpd = models.IntegerField()
	#find out how to only store selection from box here
	ed_yes = models.BooleanField()
	ed_no = models.BooleanField()
	wpap_yes = models.BooleanField()
	wpap_no = models.BooleanField()
	cz_yes = models.BooleanField()
	cz_no = models.BooleanField()
	czp_yes = models.BooleanField()
	czp_no = models.BooleanField()
	city_yes = models.BooleanField()
	city_no = models.BooleanField()
	city_name = models.TextField()
	#file